### PR TITLE
Gmail Ui

### PR DESCRIPTION
**Pull request by JeetDalal**
# Description
Gmail Ui with flutter

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)
Created a Gmail UI clone with flutter.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
There is overflow issue and only page is present. please make the detail and other nav page

**Comment by tanmoy27112000** [comment]
Simulator Screen Shot - iPhone 14 Pro Max - 2022-10-17 at 23 07 58

**Comment by JeetDalal** [comment]
Hi @tanmoy27112000 , I forgot to save the changes I made will save it and resend it.

**Review by JeetDalal — COMMENTED** [review]
Hi @tanmoy27112000,
The following changes have been made : 
1. Once the application opens you can swipe left to view google Meet and then swipe right to return to the emails page.
2. You can tap on mail to view the mail in detail.

**Review by tanmoy27112000 — COMMENTED** [review]
resolve the conflicts please

**Pull request closed without merging**
