### PR TITLE
Hotel App UI

### PR DESCRIPTION
**Pull request by Tosin2289**
# Description

I created an hotel app UI with flutter this Ui contains both the home screen and the details screen

Fixes # (issue)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

Screenshots of the app UI
Screenshot_1696562239
Screenshot_1696597161
Screenshot_1696597165
Screenshot_1696597170

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
The button in the first screen shot is cutting out.fix that please

**Comment by Tosin2289** [comment]
okay on it

**Comment by Tosin2289** [comment]
button cut out fixed 
Screenshot_1696618158

**Comment by tanmoy27112000** [comment]
attach the corresponding issue in the comment

**Comment by Tosin2289** [comment]
issue #126

**Comment by tanmoy27112000** [comment]
you have made changes in all the files and folders. please revert those changes and only add your ui folder

**Review by tanmoy27112000 — CHANGES_REQUESTED** [review]
only add your folder and remove all the changes

**Comment by Tosin2289** [comment]
Changes have been reverted

**Review by tanmoy27112000 — APPROVED** [review]

**Pull request merged**
