### PR TITLE
Facebook_UI

### LINKED ISSUE #105: Facebook Ui
I want to add FaceBook UI
Like this ..
image

Please assign this , I am interested to contribute in hacktoberfest_23 : )

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Here you go the Facebook UI Part Code _Flutter   ,  issue #105 

Screenshot 2023-10-03 133110

WhatsApp Image 2023-10-03 at 2 35 30 PM

Please consider this and merge It _Hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
Kindly inform incase of further modifications : )

**Review by tanmoy27112000 — APPROVED** [review]

**Comment by tanmoy27112000** [comment]
Great thanks for contributing. Hope to see more from your side.!!!

**Comment by Bharath-KumarReddy** [comment]
Sure I will come with something new UI's : )

**Comment by Bharath-KumarReddy** [comment]
Hi.
Can you change the repo rules so that it will obey the rules of hacktoberfest_23 , My PR is excluded due to this repo is not obeying the laws or rules of hacktoberfest_23

**Comment by tanmoy27112000** [comment]
what are the rules they have enforced?

**Pull request merged**
