### PR TITLE
friday_virtual_assistant

### LINKED ISSUE #113: Allan_Voice_assistant , Chatgpt along with Image generation
Allan_Voice_assistant Is an app build using Flutter and using OpenAI   API ;

It can speek to you and you ask any questions  like of chatgpt and also 

!!!!  You can ask and type to get a random image of your own imaginations for example 

A man coding in laptop on jupyter

can you assign this to me , I am interested to contribute myself in _hacktoberfest_23 : )

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
friday_Voice_assistant Is an app build using Flutter and using OpenAI API ;

-----------------i had made a PR by commit meesage      **"a virtual assistant _jarvis_friday"**----------

It can speek to you and you ask any questions like of chatgpt and also

!!!! You can ask and type to get a random image of your own imaginations for example

example --------A man coding in laptop on jupyter

But you have to create  your own **OpenAI  API** which will be available in the openai.com and assign it to API_KEY  in the code;

Once please go through this and merge it hacktoberfest_23 :)

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
attach screenshots plz

**Comment by Bharath-KumarReddy** [comment]
okay , sure )

**Comment by Bharath-KumarReddy** [comment]
screenshort

Screenshot 2023-10-08 164329


Screenshot 2023-10-08 164233

**Comment by Bharath-KumarReddy** [comment]
I had attached some images , screenshots once kindly check these : )

**Comment by Bharath-KumarReddy** [comment]
once go through this and merge it , kindly inform for further modifications : )

**Comment by tanmoy27112000** [comment]
looks good. Thanks for contribution.

**Review by tanmoy27112000 — APPROVED** [review]

**Comment by Bharath-KumarReddy** [comment]
Hi ,

In the hacktoberfest_23 website it is showing that this repo is excluded or against the rules of hacktoberfest_23 can you please change and maintain the repo according to the rules of hacktoberfest

image

image

**Comment by Bharath-KumarReddy** [comment]
Hi ,

In the hacktoberfest_23 website it is showing that this repo is excluded or against the rules of hacktoberfest_23 can you please change and maintain the repo according to the rules of hacktoberfest

image

image

**Comment by Bharath-KumarReddy** [comment]
Can you please change the repo in such a way that it should obey the rules of hacktoberfest_23 ____

As, This PR is excluded, due to this repo is not obeying the rules of hacktoberfest_23

**Pull request merged**
