### PR TITLE
World time app done

### PR DESCRIPTION
**Pull request by kaushal1717**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

## Screenshots

WhatsApp Image 2023-10-07 at 4 16 53 PM (1)
WhatsApp Image 2023-10-07 at 4 16 53 PM
WhatsApp Image 2023-10-07 at 4 16 54 PM

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
please add screenshots

**Comment by kaushal1717** [comment]
screenshots added

**Comment by tanmoy27112000** [comment]
you have added reference to the folder not the actual folder. please check and fix the PR

**Comment by kaushal1717** [comment]
my bad, changing it

**Pull request closed without merging**
