### PR TITLE
add Crypto_app_ui and manage some dependencies

### PR DESCRIPTION
**Pull request by Ankush-Paul-02**
# Description

I've added a crypto app UI which fetch data from API and manage some dependencies

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
please add screenshots

**Comment by Ankush-Paul-02** [comment]
my screenshots link
https://imgur.com/a/FVlc9IP

**Comment by tanmoy27112000** [comment]
Looks good. Thanks for your contribution!!!

**Comment by Ankush-Paul-02** [comment]
ok sir

**Pull request closed without merging**
