### PR TITLE
Guitar UI

### LINKED ISSUE #104: Guitar Ui
I want to add an attractive Guitar UI

Like these and much more 

Guitar UI

Please assign this , I am interested to contribute my self in hacktoberfest _23 : )

### PR DESCRIPTION
**Pull request by Bharath-KumarReddy**
Here you go the Guitar Ui

Guitar UI

Once please check this and merge it _Hacktoberfest_23 : )

### CODE REVIEW

**Comment by Bharath-KumarReddy** [comment]
Okay I will add some more components : )

**Comment by Bharath-KumarReddy** [comment]
Here I Made a PR of taskPlanning_app which I buid using flutter .

User authentication using firebase and all crud operations;


Once Go through this and merge It _hacktoberfest_23 : )

**Review by tanmoy27112000 — APPROVED** [review]

**Comment by Bharath-KumarReddy** [comment]
Hi ,

In the hacktoberfest_23 website it is showing that this repo is excluded or against the rules of hacktoberfest_23 can you please change and maintain the repo according to the rules of hacktoberfest

image

**Comment by Bharath-KumarReddy** [comment]
Hi.
Can you change the repo rules so that it will obey the rules of hacktoberfest_23 , My PR is excluded due to this repo is not obeying the laws or rules of hacktoberfest_23

**Pull request merged**
