### PR TITLE
Spotify_UI

### PR DESCRIPTION
**Pull request by dubey2709**
Added a basic UI of Spotify

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
Is it android only?

**Comment by dubey2709** [comment]
Yes because development of ios apps need Mac which is a limitation for me

**Comment by tanmoy27112000** [comment]
This repo is only for flutter projects

**Comment by tanmoy27112000** [comment]
can you create the same thing with flutter?

**Comment by dubey2709** [comment]
Sir it is made using flutter but only compatible with Android OS

**Comment by dubey2709** [comment]
Everyone needs X code which is installed in Mac only to create ios apps using flutter

**Comment by dubey2709** [comment]
In short it's an android app made using fluttet

**Comment by tanmoy27112000** [comment]
please can you add other 3 pages search, library and the profile page. and you can just create a project with IOS compatibility for that Xcode is not necessary.

**Pull request closed without merging**
