### PR TITLE
E-commerce app design

### PR DESCRIPTION
**Pull request by Ayeshashaik759**
# Description

I have designed the front-end part of E-commerce flower shop. Here I used the technologies HTML, CSS, JAVASCRIPT.

Fixes issue #2

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I used visual studio code live server and chrome browser  to see output design and make responsive website
- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
@Ayeshashaik759 this is not a flutter project.

**Comment by tanmoy27112000** [comment]
@Ayeshashaik759 you need to create a flutter app with the e-commerce UI

**Comment by Ayeshashaik759** [comment]
I will re submit it soon

**Comment by tanmoy27112000** [comment]
@Ayeshashaik759  sure

**Pull request closed without merging**
