### PR TITLE
Hangman in flutter

### PR DESCRIPTION
**Pull request by JeetDalal**
# Description
Complete Hangman game in flutter.

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# How Has This Been Tested?
The test were done on the application with an android emulator.

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
The emulator used was google pixel 4.

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by tanmoy27112000** [comment]
@JeetDalal  you have deleted the amazon ui folder too . please add your code in and not delete anything else

**Comment by JeetDalal** [comment]
Ok I will make the necessary changes and send it back .

**Review by JeetDalal — COMMENTED** [review]
added removed file to the project.

**Comment by tanmoy27112000** [comment]
@JeetDalal please check the hangman folder it Is not opening and no file is showing there

**Review by JeetDalal — COMMENTED** [review]
I have made the necessary changes please let me know if there is any other problem.

**Review by tanmoy27112000 — APPROVED** [review]
All good!

**Pull request merged**
