### PR TITLE
Furrl UI containing their UI and a new feature called collage maker f…

### PR DESCRIPTION
**Pull request by No0b-master**
# Description
Basic and static UI of [Furrl](https://play.google.com/store/apps/details?id=com.furrl.flutter_app)  Application, which is an e-commerce platform for unique and quirky clothes that matches your vibe, this UI contains their home page including genre section and post section, This Ui also has a collage maker written only in dart, (The only dependency is image_picker)

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Manual testing

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by No0b-master** [comment]
Sorry forgot to insert Screenshots in the PR 
SS1
SS2
SS3
SS4
SS5
SS6

**Comment by tanmoy27112000** [comment]
crate a issue for this

**Comment by No0b-master** [comment]
Created #124

**Review by tanmoy27112000 — APPROVED** [review]

**Comment by tanmoy27112000** [comment]
Looks great!!! thanks for contribution. #happyHactoberfest

**Comment by No0b-master** [comment]
@tanmoy27112000 brother , I have a question, why in the hactober website they're saying this repos have been excluded, also all the repos that I've been contributing are all excludes, do you know the real reason for it

**Pull request merged**
